name: GitHub Actions CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TEST_ORGANIZATION: 'kfcampbell-terraform-provider'
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make tools
      - run: make lint
      - run: make website-lint
      - run: make build
      - run: make test
